// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAabDxTcDqs8aJRaR_ygepA4sDW9jCU2J4',
    appId: '1:28299403503:web:d75f07ed915ebe1bf63b1a',
    messagingSenderId: '28299403503',
    projectId: 'login1-adfa9',
    authDomain: 'login1-adfa9.firebaseapp.com',
    storageBucket: 'login1-adfa9.firebasestorage.app',
    measurementId: 'G-2PJJK1M3N2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyI-6QnhsOwtAcpOAaRkeUD8WaeAbfL_E',
    appId: '1:28299403503:android:65ff8fa66735b2abf63b1a',
    messagingSenderId: '28299403503',
    projectId: 'login1-adfa9',
    storageBucket: 'login1-adfa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrCI50KhN-BvIkOw0Jq2OuDK1uevNMzKo',
    appId: '1:28299403503:ios:2295ba86c384a1faf63b1a',
    messagingSenderId: '28299403503',
    projectId: 'login1-adfa9',
    storageBucket: 'login1-adfa9.firebasestorage.app',
    androidClientId: '28299403503-4ippq8h91lu8c3ll3m0e2jfui7hpvkt5.apps.googleusercontent.com',
    iosClientId: '28299403503-4ash70lm2tvlc5bpc0qucsffnsetmuqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.crud',
  );

}